# .slather.yml
#coverage_service: cobertura_xml
xcodeproj: UpComingMovies.xcodeproj
workspace: UpComingMovies.xcworkspace
scheme: UpComingMovies
#configuration: TestedConfiguration
#source_directory: UpComingMovies
#output_directory: path/to/xml_report
source_files:
  - '*ViewModel.swift'
ignore:
  - UpComingMovies/SdkManagers/*
  - ProjectTestsGroup/*