# Xcode

# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- develop

pool:
  vmImage: 'macos-latest'

steps:
- task: CocoaPods@0
  inputs:
    forceRepoUpdate: false
- task: Xcode@5
  inputs:
    actions: 'build'
    scheme: 'UpComingMovies'
    sdk: 'iphoneos'
    configuration: 'Develop'
    xcWorkspacePath: '**/UpComingMovies.xcworkspace'
    xcodeVersion: '10' # Options: 8, 9, 10, default, specifyPath
- task: Xcode@5
  inputs:
    actions: 'test'
    xcWorkspacePath: '**/Upcoming.xcworkspace'
    scheme: 'Upcoming'
    packageApp: false
    publishJUnitResults: true